name: C/C++ CI

on:
  push:
    branches: [ master, CI_action ]
  pull_request:
    branches: [ master, CI_action ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make ./bin/objects.a
